# fly.toml file generated for hf-redis on 2022-05-15T03:32:24Z

app = "hf-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# [[services]]
#   internal_port = 6379
#   protocol = "tcp"

[[mounts]]
  destination = "/data"
  source = "redis_server"
